In [6]:

import os
import joblib
import pandas as pd
import tensorflow as tf


2025-08-29 20:08:28.972156: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [7]:
#!pip install --upgrade pip
#!pip install tensorflow

import tensorflow as tf
print(tf.__version__)


2.20.0


In [8]:
import os

base_path = "../outputs/saved_models"

# list all experiment directories
experiments = [d for d in os.listdir(base_path) if os.path.isdir(os.path.join(base_path, d))]

# sort them by timestamp at the end of the name
experiments.sort()

# last one (most recent)
latest_experiment = experiments[-1]
latest_path = os.path.join(base_path, latest_experiment)

print("All experiments:", experiments)
print("Latest experiment:", latest_experiment)
print("Path to latest:", latest_path)


All experiments: ['experiment_baseline_standardize_20250829_154708', 'experiment_baseline_standardize_20250829_162309', 'experiment_baseline_standardize_20250829_164559', 'experiment_baseline_standardize_20250829_165106']
Latest experiment: experiment_baseline_standardize_20250829_165106
Path to latest: ../outputs/saved_models/experiment_baseline_standardize_20250829_165106


In [9]:
#encoder = joblib.load(encoder_path)
# scaler:scaler = joblib.load(scaler_path)

In [10]:
# make a pred

input_data = ''

In [11]:
# preprocess input data

In [12]:

experiment_path = latest_path

scaler_path = os.path.join(experiment_path, "scaler.pkl")
encoder_path = os.path.join(experiment_path, "encoder.pkl")

In [13]:
scaler = joblib.load(scaler_path)

/home/marcos/.local/lib/python3.10/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator StandardScaler from version 1.7.1 when using version 1.1.3. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(


In [14]:
scaler

StandardScaler()

In [15]:
from joblib import load

scaler = load(scaler_path)

# See type of scaler
print(type(scaler))

# Main learned attributes
print("mean:", getattr(scaler, "mean_", None)) # mean for every feature (we have ...around 32)
#print("scale:", getattr(scaler, "scale_", None))
print("var:", getattr(scaler, "var_", None))

# All attributes and methods
#print(dir(scaler))


<class 'sklearn.preprocessing._data.StandardScaler'>
mean: [1.41559238e+01 1.93511328e+01 9.21518750e+01 6.58153516e+02
 9.61988672e-02 1.03554531e-01 8.85161713e-02 4.88897402e-02
 1.81255273e-01 6.27087305e-02 4.09529102e-01 1.21794902e+00
 2.90134512e+00 4.10547617e+01 6.94725781e-03 2.51113359e-02
 3.16497336e-02 1.17416348e-02 2.04345078e-02 3.75897129e-03
 1.63169453e+01 2.57480273e+01 1.07621934e+02 8.86556445e+02
 1.32138906e-01 2.53280762e-01 2.71695561e-01 1.14682229e-01
 2.90017188e-01 8.38891016e-02]
var: [1.25668844e+01 1.85788022e+01 5.99698209e+02 1.26879396e+05
 2.01562007e-04 2.81310339e-03 6.48463278e-03 1.53749022e-03
 7.52674738e-04 4.73514193e-05 8.17568545e-02 3.12598201e-01
 4.38201521e+00 2.22211910e+03 8.32386721e-06 2.98804298e-04
 9.40867147e-04 3.93270921e-05 6.84521929e-05 6.59908845e-06
 2.36568213e+01 3.76441772e+01 1.15197767e+03 3.32406115e+05
 5.35499243e-04 2.45697564e-02 4.37180255e-02 4.36030274e-03
 3.76101920e-03 3.24277262e-04]


In [16]:
encoder = joblib.load(encoder_path)
encoder

{'M': 1, 'B': 0}

### daat

In [17]:
import numpy as np

In [18]:
data = np.array([17.99, 10.38, 122.8, 1001.0, 0.1184, 0.2776, 0.3001,
       0.1471, 0.2419, 0.07871, 1.095, 0.9053, 8.589, 153.4, 0.006399,
       0.04904, 0.05373, 0.01587, 0.03003, 0.006193, 25.38, 17.33, 184.6,
       2019.0, 0.1622, 0.6656, 0.7119, 0.2654, 0.4601, 0.1189])

In [19]:
data

array([1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
       3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
       8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
       3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
       1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01])

In [20]:
# preprocess data accordingly

In [21]:
# Apply scaler
scaled_data = scaler.transform(data.reshape(1,-1))

print(scaled_data)

[[ 1.08155081 -2.08131795  1.25151925  0.96250756  1.56376251  3.28148085
   2.62748217  2.50467095  2.21049416  2.32534791  2.39732511 -0.55919572
   2.71704165  2.38325769 -0.19003004  1.38428347  0.71984693  0.65831264
   1.15977455  0.94750983  1.86335844 -1.37202311  2.26801001  1.96418352
   1.29904845  2.63046891  2.10534924  2.28247559  2.77336898  1.94421821]]


/home/marcos/.local/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


### load model

In [22]:
experiment_path

'../outputs/saved_models/experiment_baseline_standardize_20250829_165106'

In [23]:
from tensorflow import keras

model_path = os.path.join(experiment_path, "model.h5")
model = keras.models.load_model(model_path)

2025-08-29 20:09:00.702558: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [25]:
y_pred_prob = model.predict(scaled_data)
y_pred_prob

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step


array([[0.9999999]], dtype=float32)

In [27]:
y_pred = (y_pred_prob > 0.5).astype(int)
y_pred

array([[1]])

In [ ]:
# M with prob. 0.9999999

In [33]:
"""
O1

first_row = df.iloc[[0]]  # keeps it as DataFrame
scaled_row = scaler.transform(first_row)


O2
import pandas as pd

first_row_np = df.iloc[0].to_numpy().reshape(1, -1)
first_row_df = pd.DataFrame(first_row_np, columns=df.columns)
scaled_row = scaler.transform(first_row_df)



"""

'\nO1\n\nfirst_row = df.iloc[[0]]  # keeps it as DataFrame\nscaled_row = scaler.transform(first_row)\n\n\nO2\nimport pandas as pd\n\nfirst_row_np = df.iloc[0].to_numpy().reshape(1, -1)\nfirst_row_df = pd.DataFrame(first_row_np, columns=df.columns)\nscaled_row = scaler.transform(first_row_df)\n\n\n\n'